The Challenge — Market Data Processor

You are building the first component of a small quantitative trading system.

A market-data feed provides the following information for six consecutive timestamps:

Mid-prices: 245.20, 246.10, 244.80, 247.35, 248.00, 247.60

Bid prices: 245.10, 246.00, 244.70, 247.25, 247.90, 247.50

Ask prices: 245.30, 246.20, 244.90, 247.45, 248.10, 247.70

Volume: 1200, 850, 2100, 1750, 950, 1400

Your strategy holds 200 shares.

Using NumPy:

Create a NumPy array for each of the four market-data series.
Calculate the bid-ask spread at every timestamp.
Calculate the value of your 200-share position at every timestamp using the mid-price.
Calculate the notional traded at every timestamp using:
Notional=Price×Volume

In [2]:
#q1 Create a NumPy array for each of the four market-data series.
import numpy as np
mid_prices = np.array([245.20, 246.10, 244.80, 247.35, 248.00, 247.60])
bid_prices = np.array([245.10, 246.00, 244.70, 247.25, 247.90, 247.50])
ask_prices = np.array([245.30, 246.20, 244.90, 247.45, 248.10, 247.70])
volume = np.array([1200, 850, 2100, 1750, 950, 1400])
#Q2 Calculate the bid-ask spread at every timestamp.
spread =  ask_prices - bid_prices 
#Q3 Calculate the value of your 200-share position at every timestamp using the mid-price.
value = mid_prices * 200 
#Q4 Calculate the notional traded at every timestamp
notional_value = mid_prices *volume
print(spread)
print(value)
print(notional_value)


[0.2 0.2 0.2 0.2 0.2 0.2]
[49040. 49220. 48960. 49470. 49600. 49520.]
[294240.  209185.  514080.  432862.5 235600.  346640. ]


The Challenge — Inspect a Multi-Asset Market Dataset

You are given market data for 4 assets across 6 timestamps.

Create the following NumPy array:

             t0      t1      t2      t3      t4      t5
Asset A    100.20   101.10  100.80  102.40  103.00  102.70

Asset B    250.50   249.80  251.20  252.10  250.90  253.40

Asset C     50.20    51.00   50.70   52.30   53.10   52.80

Asset D    780.00   782.50  781.20  785.40  789.10  788.30

Then write code that:

Prints the array.
Prints its ndim.
Prints its shape.
Prints its dtype.
Creates a second NumPy array containing the corresponding trading volumes:

1200, 1500, 900, 2100, 1750, 1300

Print the volume array's:
ndim
shape
dtype
Create a third NumPy array containing these strategy returns:

0.004, -0.002, 0.006, 0.001, -0.003, 0.002

Inspect its ndim, shape, and dtype.

In [8]:
#Q1
import numpy as np
assets = np.array([
    [100.20, 101.30, 100.80, 102.40, 103.00, 102.70],
    [250.50, 249.80, 251.20, 252.10, 250.90, 253.40],
    [50.20,  51.00,  50.70, 52.30, 53.10, 52.80],
    [780.00, 782.50, 781.20, 785.40, 789.10, 788.30]
])
print(assets)
print(assets.ndim)
print(assets.dtype)
print(assets.shape)
#Q2
trading_values = np.array([1200, 1500, 900, 2100, 1750, 1300])
print(trading_values.ndim, trading_values.dtype, trading_values.shape)
trading_strat = np.array([0.004, -0.002, 0.006, 0.001, -0.003, 0.002])
#Q3
print(trading_strat.ndim)
print(trading_strat.shape)
print(trading_strat.dtype)

[[100.2 101.3 100.8 102.4 103.  102.7]
 [250.5 249.8 251.2 252.1 250.9 253.4]
 [ 50.2  51.   50.7  52.3  53.1  52.8]
 [780.  782.5 781.2 785.4 789.1 788.3]]
2
float64
(4, 6)
1 int64 (6,)
1
(6,)
float64


In [ ]:
import numpy as np
market_prices = np.array([
    [100.2, 101.5, 100.8, 102.3, 103.1, 102.7, 104.0, 105.2],
    [250.4, 249.8, 251.2, 252.5, 251.9, 253.1, 254.6, 255.0],
    [50.1,  50.8,  51.2,  50.6,  52.0,  52.4,  51.9,  53.1],
    [780.0, 782.5, 781.2, 785.4, 789.1, 788.3, 790.5, 792.0]
])
#q1
market_prices[0:1]
#q2
market_prices[-1]
#q3
market_prices[1:2,5]



array([253.1])

Build one script that:
Print the original returns.shape.
Reshape the data into a 6 × 4 asset-by-time matrix.
Print the new matrix and its shape.
Reshape the same data into a 4 × 6 time-by-asset matrix.
Print its shape.
Create a separate array of 8 execution prices:

In [17]:
import numpy as np
returns = np.array([
    0.004, -0.002, 0.006, 0.001,
    -0.003, 0.002, 0.005, -0.001,
    0.003, 0.004, -0.002, 0.006,
    0.001, -0.004, 0.002, 0.003,
    -0.001, 0.005, 0.002, -0.003,
    0.004, 0.001, -0.002, 0.005
])
#q1
print(returns)
#q2
np.shape(returns)
#q3
returns_6x4=returns.reshape(6,4)
print(returns_6x4)
print(returns_6x4)
#q4
returns4x6=returns.reshape(4,6)
print(returns4x6)
np.shape(returns4x6)




[ 0.004 -0.002  0.006  0.001 -0.003  0.002  0.005 -0.001  0.003  0.004
 -0.002  0.006  0.001 -0.004  0.002  0.003 -0.001  0.005  0.002 -0.003
  0.004  0.001 -0.002  0.005]
[[ 0.004 -0.002  0.006  0.001]
 [-0.003  0.002  0.005 -0.001]
 [ 0.003  0.004 -0.002  0.006]
 [ 0.001 -0.004  0.002  0.003]
 [-0.001  0.005  0.002 -0.003]
 [ 0.004  0.001 -0.002  0.005]]
[[ 0.004 -0.002  0.006  0.001]
 [-0.003  0.002  0.005 -0.001]
 [ 0.003  0.004 -0.002  0.006]
 [ 0.001 -0.004  0.002  0.003]
 [-0.001  0.005  0.002 -0.003]
 [ 0.004  0.001 -0.002  0.005]]
[[ 0.004 -0.002  0.006  0.001 -0.003  0.002]
 [ 0.005 -0.001  0.003  0.004 -0.002  0.006]
 [ 0.001 -0.004  0.002  0.003 -0.001  0.005]
 [ 0.002 -0.003  0.004  0.001 -0.002  0.005]]


(4, 6)

In [22]:
import numpy as np
market_data = np.array([
    [100.2, 101.5, 100.8, 102.3, 103.1, 102.7, 104.0, 105.2],
    [250.4, 249.8, 251.2, 252.5, 251.9, 253.1, 254.6, 255.0],
    [50.1,  50.8,  51.2,  50.6, 52.0,  52.4, 51.9, 53.1],
    [780.0, 782.5, 781.2, 785.4, 789.1, 788.3, 790.5, 792.0],
    [45.5,  46.2,  45.9, 47.1,  47.8, 47.4, 48.2, 48.6]
])
#q1
transposed_marketdata = market_data.T
print(transposed_marketdata)

[[100.2 250.4  50.1 780.   45.5]
 [101.5 249.8  50.8 782.5  46.2]
 [100.8 251.2  51.2 781.2  45.9]
 [102.3 252.5  50.6 785.4  47.1]
 [103.1 251.9  52.  789.1  47.8]
 [102.7 253.1  52.4 788.3  47.4]
 [104.  254.6  51.9 790.5  48.2]
 [105.2 255.   53.1 792.   48.6]]


Calculate the price squared for every observation.
 
Calculate the square root of every price.

Calculate the absolute value of every return.

Calculate the natural logarithm of every price.

Calculate  for every return using np.exp().

Round the logarithmic prices to 4 decimal places.

Create:

Calculate the bid-ask spread using element-wise subtraction.

Calculate the mid-price from bid and ask:

Mid-price=Bid+Ask/2

Print all resulting arrays.

In [44]:
import numpy as np 
prices = np.array([
    100.20, 101.50, 100.80, 102.30,
    103.10, 102.70, 104.00, 105.20
])
returns = np.array([
    0.004, -0.002, 0.006, -0.001,
    0.003, -0.005, 0.002, -0.004
])
#q1
squared_prices= prices**2
print(squared_prices)
#Q2
sqred_rootprices=np.sqrt(prices)
print("sqred prices of the price tab:",sqred_rootprices)

#Q3
abs_value=np.abs(returns)
print("abs value of returns are:",abs_value)
#q4
nlog_price =np.log(prices)
print("the nlog prices are:",nlog_price)
#q5
exp_returns=np.exp(returns)
print("exponential return values", exp_returns)
#q6
round_prices = np.round(nlog_price,4)
print("rounded prices of log values:", round_prices)
#q7
bid = np.array([
    100.10, 101.40, 100.70, 102.20,
    103.00, 102.60, 103.90, 105.10
])
ask = np.array([
    100.30, 101.60, 100.90, 102.40,
    103.20, 102.80, 104.10, 105.30
])
spread= ask-bid
print("spread is:",spread)
#q9
mid_price=(bid+ask)/2
print("the mid price is ",mid_price)






[10040.04 10302.25 10160.64 10465.29 10629.61 10547.29 10816.   11067.04]
sqred prices of the price tab: [10.009995   10.07472084 10.03992032 10.11434625 10.15381702 10.13410085
 10.19803903 10.25670512]
abs value of returns are: [0.004 0.002 0.006 0.001 0.003 0.005 0.002 0.004]
the nlog prices are: [4.60716819 4.6200588  4.61313836 4.62790967 4.63569939 4.63181212
 4.6443909  4.6558633 ]
exponential return values [1.00400801 0.998002   1.00601804 0.9990005  1.0030045  0.99501248
 1.002002   0.99600799]
rounded prices of log values: [4.6072 4.6201 4.6131 4.6279 4.6357 4.6318 4.6444 4.6559]
spread is: [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
the mid price is  [100.2 101.5 100.8 102.3 103.1 102.7 104.  105.2]
