The Challenge — Market Data Processor

You are building the first component of a small quantitative trading system.

A market-data feed provides the following information for six consecutive timestamps:

Mid-prices: 245.20, 246.10, 244.80, 247.35, 248.00, 247.60

Bid prices: 245.10, 246.00, 244.70, 247.25, 247.90, 247.50

Ask prices: 245.30, 246.20, 244.90, 247.45, 248.10, 247.70

Volume: 1200, 850, 2100, 1750, 950, 1400

Your strategy holds 200 shares.

Using NumPy:

Create a NumPy array for each of the four market-data series.
Calculate the bid-ask spread at every timestamp.
Calculate the value of your 200-share position at every timestamp using the mid-price.
Calculate the notional traded at every timestamp using:
Notional=Price×Volume

In [2]:
#q1 Create a NumPy array for each of the four market-data series.
import numpy as np
mid_prices = np.array([245.20, 246.10, 244.80, 247.35, 248.00, 247.60])
bid_prices = np.array([245.10, 246.00, 244.70, 247.25, 247.90, 247.50])
ask_prices = np.array([245.30, 246.20, 244.90, 247.45, 248.10, 247.70])
volume = np.array([1200, 850, 2100, 1750, 950, 1400])
#Q2 Calculate the bid-ask spread at every timestamp.
spread =  ask_prices - bid_prices 
#Q3 Calculate the value of your 200-share position at every timestamp using the mid-price.
value = mid_prices * 200 
#Q4 Calculate the notional traded at every timestamp
notional_value = mid_prices *volume
print(spread)
print(value)
print(notional_value)


[0.2 0.2 0.2 0.2 0.2 0.2]
[49040. 49220. 48960. 49470. 49600. 49520.]
[294240.  209185.  514080.  432862.5 235600.  346640. ]


The Challenge — Inspect a Multi-Asset Market Dataset

You are given market data for 4 assets across 6 timestamps.

Create the following NumPy array:

             t0      t1      t2      t3      t4      t5
Asset A    100.20   101.10  100.80  102.40  103.00  102.70

Asset B    250.50   249.80  251.20  252.10  250.90  253.40

Asset C     50.20    51.00   50.70   52.30   53.10   52.80

Asset D    780.00   782.50  781.20  785.40  789.10  788.30

Then write code that:

Prints the array.
Prints its ndim.
Prints its shape.
Prints its dtype.
Creates a second NumPy array containing the corresponding trading volumes:

1200, 1500, 900, 2100, 1750, 1300

Print the volume array's:
ndim
shape
dtype
Create a third NumPy array containing these strategy returns:

0.004, -0.002, 0.006, 0.001, -0.003, 0.002

Inspect its ndim, shape, and dtype.

In [8]:
#Q1
import numpy as np
assets = np.array([
    [100.20, 101.30, 100.80, 102.40, 103.00, 102.70],
    [250.50, 249.80, 251.20, 252.10, 250.90, 253.40],
    [50.20,  51.00,  50.70, 52.30, 53.10, 52.80],
    [780.00, 782.50, 781.20, 785.40, 789.10, 788.30]
])
print(assets)
print(assets.ndim)
print(assets.dtype)
print(assets.shape)
#Q2
trading_values = np.array([1200, 1500, 900, 2100, 1750, 1300])
print(trading_values.ndim, trading_values.dtype, trading_values.shape)
trading_strat = np.array([0.004, -0.002, 0.006, 0.001, -0.003, 0.002])
#Q3
print(trading_strat.ndim)
print(trading_strat.shape)
print(trading_strat.dtype)

[[100.2 101.3 100.8 102.4 103.  102.7]
 [250.5 249.8 251.2 252.1 250.9 253.4]
 [ 50.2  51.   50.7  52.3  53.1  52.8]
 [780.  782.5 781.2 785.4 789.1 788.3]]
2
float64
(4, 6)
1 int64 (6,)
1
(6,)
float64


In [ ]:
import numpy as np
market_prices = np.array([
    [100.2, 101.5, 100.8, 102.3, 103.1, 102.7, 104.0, 105.2],
    [250.4, 249.8, 251.2, 252.5, 251.9, 253.1, 254.6, 255.0],
    [50.1,  50.8,  51.2,  50.6,  52.0,  52.4,  51.9,  53.1],
    [780.0, 782.5, 781.2, 785.4, 789.1, 788.3, 790.5, 792.0]
])
#q1
market_prices[0:1]
#q2


array([[100.2, 101.5, 100.8, 102.3, 103.1, 102.7, 104. , 105.2]])