The Challenge — Market Data Processor

You are building the first component of a small quantitative trading system.

A market-data feed provides the following information for six consecutive timestamps:

Mid-prices: 245.20, 246.10, 244.80, 247.35, 248.00, 247.60

Bid prices: 245.10, 246.00, 244.70, 247.25, 247.90, 247.50

Ask prices: 245.30, 246.20, 244.90, 247.45, 248.10, 247.70

Volume: 1200, 850, 2100, 1750, 950, 1400

Your strategy holds 200 shares.

Using NumPy:

Create a NumPy array for each of the four market-data series.
Calculate the bid-ask spread at every timestamp.
Calculate the value of your 200-share position at every timestamp using the mid-price.
Calculate the notional traded at every timestamp using:
Notional=Price×Volume

In [2]:
#q1 Create a NumPy array for each of the four market-data series.
import numpy as np
mid_prices = np.array([245.20, 246.10, 244.80, 247.35, 248.00, 247.60])
bid_prices = np.array([245.10, 246.00, 244.70, 247.25, 247.90, 247.50])
ask_prices = np.array([245.30, 246.20, 244.90, 247.45, 248.10, 247.70])
volume = np.array([1200, 850, 2100, 1750, 950, 1400])
#Q2 Calculate the bid-ask spread at every timestamp.
spread =  ask_prices - bid_prices 
#Q3 Calculate the value of your 200-share position at every timestamp using the mid-price.
value = mid_prices * 200 
#Q4 Calculate the notional traded at every timestamp
notional_value = mid_prices *volume
print(spread)
print(value)
print(notional_value)


[0.2 0.2 0.2 0.2 0.2 0.2]
[49040. 49220. 48960. 49470. 49600. 49520.]
[294240.  209185.  514080.  432862.5 235600.  346640. ]


The Challenge — Inspect a Multi-Asset Market Dataset

You are given market data for 4 assets across 6 timestamps.

Create the following NumPy array:

             t0      t1      t2      t3      t4      t5
Asset A    100.20   101.10  100.80  102.40  103.00  102.70

Asset B    250.50   249.80  251.20  252.10  250.90  253.40

Asset C     50.20    51.00   50.70   52.30   53.10   52.80

Asset D    780.00   782.50  781.20  785.40  789.10  788.30

Then write code that:

Prints the array.
Prints its ndim.
Prints its shape.
Prints its dtype.
Creates a second NumPy array containing the corresponding trading volumes:

1200, 1500, 900, 2100, 1750, 1300

Print the volume array's:
ndim
shape
dtype
Create a third NumPy array containing these strategy returns:

0.004, -0.002, 0.006, 0.001, -0.003, 0.002

Inspect its ndim, shape, and dtype.

In [8]:
#Q1
import numpy as np
assets = np.array([
    [100.20, 101.30, 100.80, 102.40, 103.00, 102.70],
    [250.50, 249.80, 251.20, 252.10, 250.90, 253.40],
    [50.20,  51.00,  50.70, 52.30, 53.10, 52.80],
    [780.00, 782.50, 781.20, 785.40, 789.10, 788.30]
])
print(assets)
print(assets.ndim)
print(assets.dtype)
print(assets.shape)
#Q2
trading_values = np.array([1200, 1500, 900, 2100, 1750, 1300])
print(trading_values.ndim, trading_values.dtype, trading_values.shape)
trading_strat = np.array([0.004, -0.002, 0.006, 0.001, -0.003, 0.002])
#Q3
print(trading_strat.ndim)
print(trading_strat.shape)
print(trading_strat.dtype)

[[100.2 101.3 100.8 102.4 103.  102.7]
 [250.5 249.8 251.2 252.1 250.9 253.4]
 [ 50.2  51.   50.7  52.3  53.1  52.8]
 [780.  782.5 781.2 785.4 789.1 788.3]]
2
float64
(4, 6)
1 int64 (6,)
1
(6,)
float64


In [ ]:
import numpy as np
market_prices = np.array([
    [100.2, 101.5, 100.8, 102.3, 103.1, 102.7, 104.0, 105.2],
    [250.4, 249.8, 251.2, 252.5, 251.9, 253.1, 254.6, 255.0],
    [50.1,  50.8,  51.2,  50.6,  52.0,  52.4,  51.9,  53.1],
    [780.0, 782.5, 781.2, 785.4, 789.1, 788.3, 790.5, 792.0]
])
#q1
market_prices[0:1]
#q2
market_prices[-1]
#q3
market_prices[1:2,5]



array([253.1])

Build one script that:
Print the original returns.shape.
Reshape the data into a 6 × 4 asset-by-time matrix.
Print the new matrix and its shape.
Reshape the same data into a 4 × 6 time-by-asset matrix.
Print its shape.
Create a separate array of 8 execution prices:

In [17]:
import numpy as np
returns = np.array([
    0.004, -0.002, 0.006, 0.001,
    -0.003, 0.002, 0.005, -0.001,
    0.003, 0.004, -0.002, 0.006,
    0.001, -0.004, 0.002, 0.003,
    -0.001, 0.005, 0.002, -0.003,
    0.004, 0.001, -0.002, 0.005
])
#q1
print(returns)
#q2
np.shape(returns)
#q3
returns_6x4=returns.reshape(6,4)
print(returns_6x4)
print(returns_6x4)
#q4
returns4x6=returns.reshape(4,6)
print(returns4x6)
np.shape(returns4x6)




[ 0.004 -0.002  0.006  0.001 -0.003  0.002  0.005 -0.001  0.003  0.004
 -0.002  0.006  0.001 -0.004  0.002  0.003 -0.001  0.005  0.002 -0.003
  0.004  0.001 -0.002  0.005]
[[ 0.004 -0.002  0.006  0.001]
 [-0.003  0.002  0.005 -0.001]
 [ 0.003  0.004 -0.002  0.006]
 [ 0.001 -0.004  0.002  0.003]
 [-0.001  0.005  0.002 -0.003]
 [ 0.004  0.001 -0.002  0.005]]
[[ 0.004 -0.002  0.006  0.001]
 [-0.003  0.002  0.005 -0.001]
 [ 0.003  0.004 -0.002  0.006]
 [ 0.001 -0.004  0.002  0.003]
 [-0.001  0.005  0.002 -0.003]
 [ 0.004  0.001 -0.002  0.005]]
[[ 0.004 -0.002  0.006  0.001 -0.003  0.002]
 [ 0.005 -0.001  0.003  0.004 -0.002  0.006]
 [ 0.001 -0.004  0.002  0.003 -0.001  0.005]
 [ 0.002 -0.003  0.004  0.001 -0.002  0.005]]


(4, 6)

In [22]:
import numpy as np
market_data = np.array([
    [100.2, 101.5, 100.8, 102.3, 103.1, 102.7, 104.0, 105.2],
    [250.4, 249.8, 251.2, 252.5, 251.9, 253.1, 254.6, 255.0],
    [50.1,  50.8,  51.2,  50.6, 52.0,  52.4, 51.9, 53.1],
    [780.0, 782.5, 781.2, 785.4, 789.1, 788.3, 790.5, 792.0],
    [45.5,  46.2,  45.9, 47.1,  47.8, 47.4, 48.2, 48.6]
])
#q1
transposed_marketdata = market_data.T
print(transposed_marketdata)

[[100.2 250.4  50.1 780.   45.5]
 [101.5 249.8  50.8 782.5  46.2]
 [100.8 251.2  51.2 781.2  45.9]
 [102.3 252.5  50.6 785.4  47.1]
 [103.1 251.9  52.  789.1  47.8]
 [102.7 253.1  52.4 788.3  47.4]
 [104.  254.6  51.9 790.5  48.2]
 [105.2 255.   53.1 792.   48.6]]


Calculate the price squared for every observation.
 
Calculate the square root of every price.

Calculate the absolute value of every return.

Calculate the natural logarithm of every price.

Calculate  for every return using np.exp().

Round the logarithmic prices to 4 decimal places.

Create:

Calculate the bid-ask spread using element-wise subtraction.

Calculate the mid-price from bid and ask:

Mid-price=Bid+Ask/2

Print all resulting arrays.

In [44]:
import numpy as np 
prices = np.array([
    100.20, 101.50, 100.80, 102.30,
    103.10, 102.70, 104.00, 105.20
])
returns = np.array([
    0.004, -0.002, 0.006, -0.001,
    0.003, -0.005, 0.002, -0.004
])
#q1
squared_prices= prices**2
print(squared_prices)
#Q2
sqred_rootprices=np.sqrt(prices)
print("sqred prices of the price tab:",sqred_rootprices)

#Q3
abs_value=np.abs(returns)
print("abs value of returns are:",abs_value)
#q4
nlog_price =np.log(prices)
print("the nlog prices are:",nlog_price)
#q5
exp_returns=np.exp(returns)
print("exponential return values", exp_returns)
#q6
round_prices = np.round(nlog_price,4)
print("rounded prices of log values:", round_prices)
#q7
bid = np.array([
    100.10, 101.40, 100.70, 102.20,
    103.00, 102.60, 103.90, 105.10
])
ask = np.array([
    100.30, 101.60, 100.90, 102.40,
    103.20, 102.80, 104.10, 105.30
])
spread= ask-bid
print("spread is:",spread)
#q9
mid_price=(bid+ask)/2
print("the mid price is ",mid_price)






[10040.04 10302.25 10160.64 10465.29 10629.61 10547.29 10816.   11067.04]
sqred prices of the price tab: [10.009995   10.07472084 10.03992032 10.11434625 10.15381702 10.13410085
 10.19803903 10.25670512]
abs value of returns are: [0.004 0.002 0.006 0.001 0.003 0.005 0.002 0.004]
the nlog prices are: [4.60716819 4.6200588  4.61313836 4.62790967 4.63569939 4.63181212
 4.6443909  4.6558633 ]
exponential return values [1.00400801 0.998002   1.00601804 0.9990005  1.0030045  0.99501248
 1.002002   0.99600799]
rounded prices of log values: [4.6072 4.6201 4.6131 4.6279 4.6357 4.6318 4.6444 4.6559]
spread is: [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
the mid price is  [100.2 101.5 100.8 102.3 103.1 102.7 104.  105.2]


In [4]:
import numpy as np
entry_prices = np.array([
    100.20, 101.50, 100.80, 102.30, 103.10,
    102.70, 104.00, 105.20, 106.10, 105.80
])
exit_prices = np.array([
    101.20, 100.90, 101.60, 103.10, 102.40,
    103.50, 103.20, 106.00, 105.50, 107.10
])
shares = np.array([
    100, 200, 150, 100, 250,
    300, 100, 200, 150, 250
])
transaction_cost = 25
#q1 Calculates the P&L of every trade
Pnl=(exit_prices-entry_prices)*shares
print(Pnl)
#q2 Calculates the transaction-cost-adjusted P&L:
net_pnl= Pnl - transaction_cost
print(net_pnl)
#q3 Calculates the percentage return for every trade
returns= (exit_prices-entry_prices)/entry_prices
print(returns)
#q4 Converts those returns into percentages.
return_percentages = returns * 100
print(return_percentages)
#q5 Calculates the absolute return of every trade.
absolute_returns = np.abs(returns)
print(x)
#q6 Calculates the notional value of each trade using
notional_value = entry_prices * shares
print(notional_value)

[ 100. -120.  120.   80. -175.  240.  -80.  160.  -90.  325.]
[  75. -145.   95.   55. -200.  215. -105.  135. -115.  300.]
[ 0.00998004 -0.00591133  0.00793651  0.00782014 -0.00678952  0.00778968
 -0.00769231  0.00760456 -0.00565504  0.01228733]
[ 0.99800399 -0.591133    0.79365079  0.78201369 -0.67895247  0.77896787
 -0.76923077  0.76045627 -0.56550424  1.22873346]
[100. 120. 120.  80. 175. 240.  80. 160.  90. 325.]
[10020. 20300. 15120. 10230. 25775. 30810. 10400. 21040. 15915. 26450.]


In [5]:
import numpy as np
returns = np.array([
    [ 0.010, -0.020,  0.015,  0.005, -0.010],
    [ 0.020,  0.010, -0.005,  0.012,  0.008],
    [-0.015,  0.025,  0.010, -0.008,  0.020],
    [ 0.005, -0.010,  0.020,  0.015, -0.005],
    [ 0.012,  0.005, -0.010,  0.020,  0.015],
    [-0.008,  0.015,  0.005, -0.012,  0.010]
])
weights = np.array([
    0.20, 0.25, 0.15, 0.10, 0.30
])
#q1
np.shape(returns)
np.shape(weights)
#q2 & q3
weighted_returns = returns * weights
#q4
transaction_costs = np.array([
    0.001, 0.002, 0.0015, 0.0005, 0.001
])
#q5 & q6
net_returns = returns - transaction_costs
#q7
print(weighted_returns)
print(net_returns)
np.shape(weighted_returns)
np.shape(net_returns)

[[ 0.002   -0.005    0.00225  0.0005  -0.003  ]
 [ 0.004    0.0025  -0.00075  0.0012   0.0024 ]
 [-0.003    0.00625  0.0015  -0.0008   0.006  ]
 [ 0.001   -0.0025   0.003    0.0015  -0.0015 ]
 [ 0.0024   0.00125 -0.0015   0.002    0.0045 ]
 [-0.0016   0.00375  0.00075 -0.0012   0.003  ]]
[[ 0.009  -0.022   0.0135  0.0045 -0.011 ]
 [ 0.019   0.008  -0.0065  0.0115  0.007 ]
 [-0.016   0.023   0.0085 -0.0085  0.019 ]
 [ 0.004  -0.012   0.0185  0.0145 -0.006 ]
 [ 0.011   0.003  -0.0115  0.0195  0.014 ]
 [-0.009   0.013   0.0035 -0.0125  0.009 ]]


(6, 5)

In [23]:
import numpy as np
returns = np.array([
    [ 0.010, -0.020,  0.015,  0.005, -0.010],
    [ 0.020,  0.010, -0.005,  0.012,  0.008],
    [-0.015,  0.025,  0.010, -0.008,  0.020],
    [ 0.005, -0.010,  0.020,  0.015, -0.005],
    [ 0.012,  0.005, -0.010,  0.020,  0.015],
    [-0.008,  0.015,  0.005, -0.012,  0.010],
    [ 0.018, -0.005,  0.012,  0.008, -0.015],
    [ 0.003,  0.020, -0.008,  0.010,  0.005]
])
volume = np.array([
    [1200, 1500, 900, 2100, 1750],
    [1400, 1300, 1100, 1900, 1600],
    [1000, 1700, 1200, 1800, 2000],
    [1500, 1200, 1400, 2200, 1300],
    [1100, 1600, 1000, 2000, 1800],
    [1300, 1400, 1500, 1700, 1900],
    [1600, 1100, 1300, 2100, 1500],
    [1250, 1550, 1050, 1950, 1700]
])
#q1 The average return of each asset.
avg_return_asset=returns.mean(axis=0)
print(avg_return_asset)
#q2 The average return of each trading day across all assets.
avg_return_td=returns.mean(axis=1)
print(avg_return_td)
#q3 The total trading volume of each asset.
t_vol_asset=volume.sum(axis=0)
print(t_vol_asset)
#q4The total trading volume of each trading day.
t_vold= volume.sum(axis=1)
print(t_vold)
#q5 The maximum return observed for each asset.
max_return= returns.max(axis=0)
print(max_return)
#q6 The minimum return observed for each asset.
min_return= returns.min(axis=0)
print(min_return)
#q7 The overall total trading volume.
overall_tval= volume.sum()
print(overall_tval)
#q8 The overall average return.
overall_avg= returns.mean()
print(overall_avg)


[0.005625 0.005    0.004875 0.00625  0.0035  ]
[-3.46944695e-19  9.00000000e-03  6.40000000e-03  5.00000000e-03
  8.40000000e-03  2.00000000e-03  3.60000000e-03  6.00000000e-03]
[10350 11350  9450 15750 13550]
[7450 7300 7700 7600 7500 7800 7600 7500]
[0.02  0.025 0.02  0.02  0.02 ]
[-0.015 -0.02  -0.01  -0.012 -0.015]
60450
0.005050000000000001


In [1]:
import numpy as np
returns = np.array([
    0.004, -0.012, 0.025, 0.003,
    -0.031, 0.018, 0.007, -0.022,
    0.041, -0.005
])
prices = np.array([
    100.2, 101.5, 99.8, 102.3,
    103.1, 104.5, 105.2, 103.8,
    106.1, 107.3
])
trade_sizes = np.array([
    100, 500, 1500, 250,
    2000, 750, 1200, 300,
    2500, 900
])
# Q1 — Returns with absolute magnitude > 2%
large_moves = returns[np.abs(returns) > 0.02]
print("Returns with magnitude > 2%:", large_moves)
# Q2 — Positive returns > 1%
positive_returns = returns[returns > 0.01]
print("Positive returns > 1%:", positive_returns)
# Q3 — Negative returns < -1%
negative_returns = returns[returns < -0.01]
print("Negative returns < -1%:", negative_returns)
# Q4 — Prices between ₹100 and ₹105, inclusive
price_range = prices[(prices >= 100) & (prices <= 105)]
print("Prices between 100 and 105:", price_range)
# Q5 — Trades larger than 1,000 shares
large_trades = trade_sizes[trade_sizes > 1000]
print("Trades > 1000 shares:", large_trades)
# Q6 — Boolean mask for returns > 2%
return_mask = returns > 0.02
print("Return mask:", return_mask)
# Q7 — Use mask to extract corresponding returns
returns_above_2 = returns[return_mask]
print("Returns > 2%:", returns_above_2)
# Q8 — Cap returns above +3% at +3%
capped_returns = returns.copy()
capped_returns[capped_returns > 0.03] = 0.03
print("Capped returns:", capped_returns)

Returns with magnitude > 2%: [ 0.025 -0.031 -0.022  0.041]
Positive returns > 1%: [0.025 0.018 0.041]
Negative returns < -1%: [-0.012 -0.031 -0.022]
Prices between 100 and 105: [100.2 101.5 102.3 103.1 104.5 103.8]
Trades > 1000 shares: [1500 2000 1200 2500]
Return mask: [False False  True False False False False False  True False]
Returns > 2%: [0.025 0.041]
Capped returns: [ 0.004 -0.012  0.025  0.003 -0.031  0.018  0.007 -0.022  0.03  -0.005]


In [4]:
import numpy as np
#q1
rng=np.random.default_rng(42)
#q2 Generates 1,000 synthetic daily returns from a normal distribution with mean = 0.0005 standard deviation = 0.01
synthetic_daily = rng.normal(loc=0.0005,scale=0.01,size=1000) 
print(synthetic_daily)
#q3 Generates 1,000 random trading volumes between 100 and 10,000
trading_volume= rng.normal(100,1001,size=1000)
print(trading_volume)
#q4 Generates 1,000 random execution prices uniformly between 95 and 105.
ex_prices= rng.uniform(95,106,size=1000)
print(ex_prices)
#q5 Create an initial price of:
initial_price= 100
#q6 Use the generated returns to create a simulated price path using:
np.cumprod(1+synthetic_daily)
#q7 Print: the first 10 returns the first 10 volumes the first 10 execution prices,the first 10 simulated prices
prices=initial_price*np.cumprod(1+synthetic_daily )
print(prices)
print(synthetic_daily[:10])
print(trading_volume[:10])
print(ex_prices[:10])
print(prices[:10])


[ 3.54717080e-03 -9.89984106e-03  8.00451196e-03  9.90564716e-03
 -1.90103519e-02 -1.25217951e-02  1.77840403e-03 -2.66242592e-03
  3.31988425e-04 -8.03043928e-03  9.29397975e-03  8.27791935e-03
  1.16030698e-03  1.17724121e-02  5.17509342e-03 -8.09292463e-03
  4.18750784e-03 -9.08882601e-03  9.28450301e-03  7.40890137e-07
 -1.34862364e-03 -6.30929544e-03  1.27254134e-02 -1.04529482e-03
 -3.78327822e-03 -3.02133550e-03  5.82309186e-03  4.15444064e-03
  4.62732612e-03  4.80821003e-03  2.19164760e-02 -3.56415016e-03
 -4.62242729e-03 -7.63772728e-03  6.65979423e-03  1.17897229e-02
 -6.39474577e-04 -7.90156477e-03 -7.74481216e-03  7.00592788e-03
  7.93254171e-03  5.93154268e-03 -6.15509707e-03  2.82161323e-03
  1.66685809e-03  2.68688597e-03  9.21428778e-03  2.73595549e-03
  7.28913563e-03  1.17579069e-03  3.39119399e-03  6.81288226e-03
 -1.40715582e-02 -2.69671216e-03 -4.20372654e-03 -5.88877848e-03
 -2.25142251e-03  1.54494131e-02 -8.15831116e-03  1.01827835e-02
 -1.63286977e-02 -2.84885